services:
  multigym-dev-front:
    build:
      context: .
      dockerfile: Dockerfile.vps
    container_name: multigym-dev-front
    restart: unless-stopped
    profiles: ["dev"]
    env_file:
      - ./.env
    volumes:
      - ./certs:/etc/nginx/certs:ro
    networks:
      - multigym-network

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

networks:
  multigym-network:
    name: multigym-network
